version: '1'

services:
  gateway:
    build:
      context: ../..
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      args:
        SERVICE_PATH: ./gateway
    volumes:
      - ./gateway:/usr/src/server
    ports:
      - '3000:3000'
    networks:
      - happymushroomdragon

  happymushroomdragon:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./backend/HappyMushroomDragon
    volumes:
      - ./backend/HappyMushroomDragon:/usr/src/server
    networks:
      - happymushroomdragon
      - sql_server

  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    restart: always
    env_file:
      - dev.env
    ports:
      - "1433:1433"
    networks:
      - sql_server
    volumes:
      - "./data:/var/opt/mssql/data"

networks:
  happymushroomdragon:
  sql_server:
